import type { Draft, GateContext } from './types.js';

/**
 * A draft that passes all five gates against the real config/ files.
 * Tests mutate a copy of this, so every failure test isolates one rule.
 */
export const passingDraft: Draft = {
  slug: 'how-to-improve-revenue-per-visitor',
  title: 'How to improve revenue per visitor on a Shopify store',
  h1: 'How to improve revenue per visitor on a Shopify store',
  metaDescription:
    'How to improve revenue per visitor on Shopify: read live session signals, ' +
    'reorder what each shopper sees, and lift revenue without buying more traffic.',
  additionalKeywords: [],
  primaryKeyword: 'How to improve revenue per visitor',
  clusterId: 'conversion-rate',
  personaId: 'ecommerce-leadership',
  bodyMd: [
    '**TL;DR** — How to improve revenue per visitor: stop buying more traffic.',
    'Reorder what the traffic already sees. Helium merchants see 30% higher conversion.',
    '',
    '## Why more traffic stops working',
    '',
    'Every store hits the same wall. Traffic climbs and revenue does not follow.',
    'The cause is rarely the ad. It is what the shopper lands on.',
    'Your best product sits below the fold. The shopper never scrolls.',
    'You paid for that visit twice: once to the platform, once to indifference.',
    '',
    'Most teams respond by buying more visits. That raises the bill and nothing else.',
    'The visits were never the problem. The first screen was.',
    '',
    '## Session-aware merchandising',
    '',
    'Session-aware merchandising is reordering products from live behaviour,',
    'not from a segment decided last quarter.',
    'The store reads the session as it happens. Then it reorders the grid.',
    'A shopper who filters by size sees stock in that size first.',
    'A returning shopper sees what they abandoned, not the homepage carousel.',
    '',
    'Helium reads 40+ site-level signals to decide what belongs on that first screen.',
    'It scores each SKU on buy chance, risk, geo and time fit, and stock.',
    'Those scores refresh daily as the data shifts underneath them.',
    '',
    '## What the numbers actually move',
    '',
    'Revenue per visit is the metric that survives a traffic dip.',
    'Sessions flatter you. Revenue per visit does not.',
    'W for Woman saw revenue per visit rise 27% in four weeks.',
    'Nothing about their traffic changed. What shoppers saw first did.',
    '',
    'The mechanism is unglamorous and that is the point.',
    'No new channel. No new creative. No rebuild.',
    'The catalogue you already own, ordered for the person actually looking at it.',
    '',
    '## Where teams get this wrong',
    '',
    'The common mistake is treating the first fold as a design question.',
    'It is a ranking question wearing a design costume.',
    'A prettier hero does not help a shopper who wants a specific thing.',
    'Ordering does.',
    '',
    'The second mistake is testing this like a banner.',
    'One variant, four weeks, a p-value at the end.',
    'Session-aware ordering does not have a variant. It has a policy.',
    'You judge a policy on the distribution it produces, not on a single cell.',
    '',
    'The third is measuring the wrong window. Personalisation begins in 15 days here,',
    'because the models need that long to learn a catalogue.',
    'Teams that judge it at day four conclude nothing happened, and they are right.',
    'Nothing had.',
    '',
    '## What to change first',
    '',
    'Start with the first fold on your highest-traffic collection.',
    'Measure revenue per visit, not sessions.',
    'Give it two weeks before you judge anything.',
    'Then extend the same logic to search and to the cart.',
    '',
    'Most stores find the same thing. The products that convert were always there.',
    'They were just three scrolls too far down.',
    '',
    'Expect the first fold to change more than you are comfortable with.',
    'That is the system doing its job, not a bug in the rules you wrote.',
    'Your merchandisers keep the veto. They stop setting the order by hand.',
    'That trade is the whole product.',
    '',
    'One caution. Do not run this alongside a sitewide discount and then ask',
    'which one moved the number. You will not be able to tell, and neither will we.',
    '',
    'See how [Helium merchandising](https://www.gethelium.co/merchandising) orders your',
    'catalogue per shopper.',
    '',
    'Book a call and we will show you the fold your shoppers never scroll past.',
  ].join('\n'),
};

export const emptyContext: GateContext = { existingSlugs: [], targetedKeywords: [] };

export const draft = (overrides: Partial<Draft> = {}): Draft => ({ ...passingDraft, ...overrides });
